### ISSUE TITLE
How to retrieve all styles and scripts

### ISSUE THREAD

**Issue by bruno-barros** [Giuseppe-Mazzapica/Occipital#1]
Hey Giuseppe.
I want to retrieve all assets added via Occipital. I saw the getStyle(), but it returns just one by it identifier.
How could I get all assets registered by Occipital?
Tnks.

**Comment by Giuseppe-Mazzapica** [comment]
There is no API method, but you can use

```
Brain\Assets::getContainer()->getStyles(); // for styles
Brain\Assets::getContainer()->getScripts(); // for scripts
```

**Comment by bruno-barros** [comment]
OK, thank you.
I got an array with four items, and only one item has values, the others are empty.
```
$css = Brain\Assets::getContainer()->getStyles();
// $css[1] <- this isn't empty
```
Is this an expected behavior?
